services:
  - type: web
    name: columnfort
    env: docker
    plan: free
    autoDeploy: true
    # Dockerfile을 그대로 사용하므로 buildCommand/startCommand는 비움
    buildCommand: ""
    startCommand: ""
    # 배포 직후(서비스 시작 전에) 1회 실행됨
    releaseCommand: "php artisan migrate --force"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      # 아래 ENV들은 대시보드에서 이미 넣었다면 생략 가능 (sync:false는 대시보드 값 사용)
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
